AspDotNetMVC/Models/ContactFormModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspDotNetCoreMVC.Models
{
    public class ContactFormModel
    {
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(500)]
        public string Message { get; set; }
    }
}

AspDotNetMVC/Models/ErrorViewModel.cs
namespace AspDotNetCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspDotNetMVC/Models/PersonViewModel.cs
using AspDotNetCoreMVC.Data;

namespace AspDotNetCoreMVC.Models
{
    public class PersonViewModel
    {
        public string Name{ get; set; }
        public int Age { get; set; }
        public PersonViewModel(Person person)
        {
            Name = $"{person.FirstName} {person.LastName}";
            Age = DateTime.Now.Year - person.DateOfBirth.Year;
        }
    }
}

AspDotNetMVC/Models/TodoItem.cs
namespace AspDotNetCoreMVC.Models
{
    public class TodoItem
    {
        public int UserId { get; set; }
        public string Text { get; set; }
    }
}

AspDotNetMVC/Controllers/ContactController.cs
using AspDotNetCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspDotNetCoreMVC.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ContactFormModel model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Success");
            }

            return View(model);
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

AspDotNetMVC/Controllers/HomeController.cs
using AspDotNetCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using AspDotNetCoreMVC.Data;
using AspDotNetCoreMVC.Filters;

namespace AspDotNetCoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPersonService _personService;

        public HomeController(ILogger<HomeController> logger, IPersonService personService)
        {
            _logger = logger;
            _personService = personService;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return ViewComponent("TopProducts", new { count = 10 });
        }

        // /home/person
        public IActionResult Person()
        {
            var persons = _personService.GetAll();
            var viewModel = new PersonViewModel(persons.First());
            ViewData["LuckyNumber"] = 20;
            ViewBag.HomeAddress = "123 Main St, Springfield, USA";

            return View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult BlogPost()
        {
            return View();
        }

        public IActionResult ToDo()
        {
            return View();
        }

        [HttpPost]
        [ValidateModel]
        public IActionResult Create(TodoItem item)
        {
            return Ok($"Item '{item.Text}' created.");
        }
    }
}

AspDotNetMVC/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspDotNetCoreMVC.Controllers
{
    public class NewsController : Controller
    {
        public IActionResult Atricle(string article)
        {
            return View();
        }
    }
}

AspDotNetMVC/ViewComponents/TopProductsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using AspDotNetCoreMVC.Services;
using System.Runtime.CompilerServices;

namespace AspDotNetCoreMVC.ViewComponents
{
    public class TopProductsViewComponent : ViewComponent
    {
        private readonly IProductService _productService;
        public TopProductsViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var products = await _productService.GetTopProductsAsync(count);
            return View(products);
        }
    }
}

AspDotNetMVC/Views/Home/BlogPost.cshtml
@{
    Layout = "_ContextLayout";
}

<h1>Important</h1>
<p>C# devlopers are the best!</p>

AspDotNetMVC/Views/Home/Index.cshtml
@inject ILocalizedText LocalizedText

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="message">
        <h1 class="display-4">@LocalizedText.GetPageTitle("de")</h1>
        <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>
    <p>
        <div>Tag Helpers:</div>
        <a asp-controller="Home" asp-action="Privacy">Privacy</a>
    </p>

    <p>
        <div>Url Helper: Action</div>
        <a href="@Url.Action("Privacy", "Home")">Privacy</a>
    </p>

    <p>
        <div>Url Helper: Action Link</div>
        <a href="@Url.ActionLink("Privacy", "Home")">Privacy</a>
    </p>

    @await Component.InvokeAsync("TopProducts", new { count = 5 })
</div>

AspDotNetMVC/Views/Home/Person.cshtml
@model PersonViewModel

@{
    ViewData["TItle"] = Model.Name;
}

<h1>@Model.Name</h1>
<p><b>Age:</b>@Model.Age <u>(View Model - The Best Solution)</u></p>
<p>Lucky Number: @ViewData["LuckyNumber"] <u>(View Data - Not Recommended)</u></p>
<p>Home Address:@ViewBag.HomeAddress <u>(View Bag - Recommended Over ViewData)</u></p>

AspDotNetMVC/Views/Home/Todo.cshtml
@model TodoItem

@{
    ViewData["Title"] = "Todo"; 
}

<h2>Todos</h2>

<form asp-action="Create" method="post">
    <div style="margin-bottom:10px">
        <label class="label" asp-for="Text"></label>
        <input asp-for="Text" class="form-control" />
    </div>
    <div style="margin-bottom:10px">
        <label class="label" asp-for="UserId"></label>
        <input type="text" asp-for="UserId" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

AspDotNetMVC/Views/Shared/Components/TopProducts/Default.cshtml
@using AspDotNetCoreMVC.Services

@model IEnumerable<AspDotNetCoreMVC.Data.Product>

@{
    var products = Model;
}

<div style="display:flex; flex-direction:column">
    <h2>Top Products</h2>
    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in products)
            {
                <tr>
                    <td>@product.Name</td>
                    <td>@product.Price.ToString("C")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

AspDotNetMVC/Views/Shared/_ContextLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspDotNetCoreMVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspDotNetCoreMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspDotNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspDotNetCoreMVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspDotNetCoreMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspDotNetCoreMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Person">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BlogPost">Blog Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ToDo">ToDo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AspDotNetCoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>